### ISSUE TITLE
Move to PostgreSQL

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#12]
It would be nice to move to sqlite. The app should be cross-platform.

Currently blocked, because of [SQLite EF Core Database Provider Limitations](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations)

**Comment by jenia90** [comment]
Hi,
Why not use something more advanced like MySQL or PostgreSQL? Both have docker images that can be used and both are cross-platform so you can run them locally. Also, AFAIK, they have pretty good support in EF Core, even though not an official Microsoft EF database provider.

**Comment by amoraitis** [comment]
@jenia90 Yes, postgreSQL seems to be the best option here. I am updating the issue.

**Comment by kebin** [comment]
@amoraitis , @jenia90 Any updates on moving to pgsql? Being able to develop/run on macos would be awesome. If this is stalled, I can pick this one up.

**Comment by amoraitis** [comment]
> @amoraitis , @jenia90 Any updates on moving to pgsql? Being able to develop/run on macos would be awesome. If this is stalled, I can pick this one up.


Yes , this one is assigned to you now. I will work on finishing with #59,

**Comment by kebin** [comment]
@amoraitis  [Pull request ](https://github.com/amoraitis/TodoList/pull/65)created for this.

**Comment by amoraitis** [comment]
> @amoraitis [Pull request ](https://github.com/amoraitis/TodoList/pull/65)created for this.

Thank you very much for your contribution. I have also updated feature/#44-todolist-api. As you may have  noticed, we are restructuring the project, so we can support Xamarin.

**Comment by amoraitis** [comment]
Oh @kebin , can you please apply the same changes to the branch feature/#44-todolist-api branch, too? So, we can completely move to PostgreSQL?

**Comment by kebin** [comment]
@amoraitis Awesome! I just created a pull request for this. Thanks.

**Comment by amoraitis** [comment]
Thank you!
