### ISSUE TITLE
[Feature] Add calendar view for Todos in the home page

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#15]
**Is your feature request related to a problem? Please describe.**
It would be nice, if we had a calendar view option in the home page, showing the todos of the current month.

**Describe the solution you'd like**

- Frontend
Use [bootstrap's tabs like buttons](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior) (I think that this requires bootstrap 4, in this case the present is blocked by #13 ) to navigate between views. Also, for the calendar view, use [tables](https://getbootstrap.com/docs/4.0/content/tables/), at first, and see how that works. In each cell, we want only the titles of the Todos with each links at `Todos/Details?id={id}`

- Backend
Another endpoint should be created at `Todos/{month}-{year}` to access the required resources.

**Describe alternatives you've considered**
Use an existing calendar view, but in this case, let's build something from scratch...

**Additional context**
We need a viewmodel for the new page, to request only the data we need.

**Comment by pirland** [comment]
I can work on this once my changes in https://github.com/amoraitis/TodoList/pull/51 pass.
