### ISSUE TITLE
Create a public home, about and contact us page

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#27]
**Is your feature request related to a problem? Please describe.**
We could add our own public pages instead of using the template's defaults.

**Describe the solution you'd like**
Create a minimal page for each one. Make use of the existing functionality in the `HomeController.cs` and the existing razor pages under the `Views/Home/` directory

**Comment by mr-nand** [comment]
@amoraitis I would like to work on this issue.

**Comment by Neuron34** [comment]
Can I work on this issue

**Comment by amoraitis** [comment]
> Can I work on this issue

Of course, use the existing libraries, please.

**Comment by Neuron34** [comment]
hey bro I think your Repo is not loading properly 
![RepoError](https://user-images.githubusercontent.com/42699838/66744059-161e4400-ee99-11e9-95e8-2a201ff82947.png)

**Comment by amoraitis** [comment]
> hey bro I think your Repo is not loading properly
> ![RepoError](https://user-images.githubusercontent.com/42699838/66744059-161e4400-ee99-11e9-95e8-2a201ff82947.png)

@Neuron34 could you please share the output?

**Comment by pirland** [comment]
I'm not sure of the etiquette here, but it looks like I should have posted here first.  I just created a pull request with rudimentary versions of these three pages:
https://github.com/amoraitis/TodoList/pull/39
Sorry if I stepped on anybodys toes.

**Comment by pirland** [comment]
Also I had the same issue with the projects not loading in Visual Studio.   I fixed it by deleting the .vs folder.

**Comment by amoraitis** [comment]
@pirland Your contributions are welcome, I am going to review them now, unless if there is more work to be done. I can see that the tests aren't updated.

Also, I am not sure why you cannot build the project, I haven't pushed a `.vs\` folder here.

Also, please `git rebase develop` in your branch. Don't merge develop. We would like a clear history of commits.

**Comment by pirland** [comment]
Thanks.  I just noticed the that the tests were failing.  I can fix them and recommit.  Do you have a preference for testing controllers that return a static view?  It was previously testing the ViewData, but I removed that since it was placeholder text.

I'll use rebase from here on out.

**Comment by pirland** [comment]
Should be good to go now.
