### ISSUE TITLE
Create ToDo from web is failing due to UserId is null 

### ISSUE THREAD

**Issue by vinothrao** [amoraitis/TodoList#36]
**Describe the bug**
When creating ToDo item from web it is failing due to UserID is null .

**To Reproduce**
Goto Create
Submit to item

**Expected behavior**
It should save the item.

**Screenshots**
![image](https://user-images.githubusercontent.com/5294130/66253110-d2348c00-e780-11e9-83a6-9e4f05924157.png)

**Additional context**
I think we should segregate DB models and viewmodels.  Then do automapper and save. Please confirm and let me know.

**Comment by vinothrao** [comment]
Did you get a chance to look into it.

**Comment by amoraitis** [comment]
> Did you get a chance to look into it.

@vinothrao i will keep you posted.

**Comment by amoraitis** [comment]
> Did you get a chance to look into it.
@vinothrao 

OK, this might happen, because I updated the project dependencies and `ModelState`, might not accept a partial object of type `TodoItem` in ASP.NET Core 2.2.

I am going to change the implementation and create a ViewModel for this action. Have a look at my latest commit
