### ISSUE TITLE
Project architecture improvements: Introduce TodoList.Core

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#42]
We would like to separate the concerns for this project.

`TodoList.Core`: This is where all the logic will be(model classes, services, repositories, etc.)

**Comment by ncindric** [comment]
Hi, I would like to take a shot at this and, if this one is accepted #44. Would you be ok with that?

**Comment by amoraitis** [comment]
@ncindric Of course, take your time and open a PR.
