### ISSUE TITLE
Project architecture improvements: Introduce TodoList.Api

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#44]
`TodoList.Api`: Here we would like to expose the services with various endpoints and consume the endpoints at `TodoList.Web`(I will open a new issue for this) and, why not, to create a new cross-platform mobile app.

**Comment by jenia90** [comment]
Hi, maybe instead of splitting #45 I could take this issue.

**Comment by amoraitis** [comment]
Yes, whatever you like @jenia90
