### ISSUE TITLE
[Feature] Extend calendar view functionality

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/TodoList#64]
**Is your feature request related to a problem? Please describe.**
Right now(as implemented in #15 , the calendar view shows only a badge with the number of todos of each day.

**Describe the solution you'd like**
Extend UI functionality and make the badge clickable. 
When the user clicks that badge, open a pop-up or append below the calendar a view to show details about those todos.

**Comment by VBorisof** [comment]
Hello! I have created a PR for this: 
https://github.com/amoraitis/TodoList/pull/71

Please let me know if I can be of further help.

**Comment by amoraitis** [comment]
Reviewing now.
