### ISSUE TITLE
[Suggestion] Microsoft.Web.LibraryManager.Cli should be mentioned within the setup steps.

### ISSUE THREAD

**Issue by WillSams** [amoraitis/TodoList#69]
When attempting to build the solution on another machine, I realized Libman was not available.  As part of the setup step (before 'dotnet build'), users may need to execute 'dotnet tool install -g Microsoft.Web.LibraryManager.Cli'.

**Comment by amoraitis** [comment]
Although most people working/learning dotnet may have already installed that tool. I guess this is a nice addition for those who haven't done so yet.

Thank you anyway!

**Comment by WillSams** [comment]
Still, it's a dependency and a needed step if it's not already installed.  A Windows UI or microservices developer would probably not have that tool installed.  As I mentioned myself, I did not have it install on the machine I downloaded the repository on so it's a necessary step.

**Comment by amoraitis** [comment]
I agree. Your PR is merged now.
